project:
  type: website
  output-dir: docs

website:
  title: "Real Good Docs"
  favicon: assets/images/logo/favicon.ico
  page-navigation: true
  search: true

  navbar:
    background: black
    type: dark 
    border: true
    right:
      - href: https://data.realgoodresearch.com
        text: Data
      - href: https://docs.realgoodresearch.com
        text: Docs
      - href: https://github.com/realgoodresearch
        target: _blank
        text: Code
      - href: https://realgoodresearch.com
        text: Home
    left:
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Research"
        href: research/index.qmd
  
  sidebar: 
    - id: bayesian-intro-sidebar
      title: "Bayesian Intro"
      path: teaching/bayesian_intro/
      contents: 
        - text: "Welcome"
          href: teaching/bayesian_intro/overview.qmd
        - text: "Table of Contents"
          href: teaching/bayesian_intro/toc.qmd
        - text: "Getting Started" 
          href: teaching/bayesian_intro/getting-started.qmd
        - section: "Lecture Slides"
          contents: 
          - text: "Intro to Bayesian Inference"
            href: teaching/bayesian_intro/lecture-intro-to-bayesian-inference.qmd
          - text: "GLMs and Hierarchical Models"
            href: teaching/bayesian_intro/lecture-glm-and-hierarchical-models.qmd
        - section: "Practical Tutorials"
          contents:
          - text: "Model of the Mean"
            href: teaching/bayesian_intro/practical-model-of-the-mean.qmd
          - text: "Exploring Posteriors, Likelihoods, and Priors"
            href: teaching/bayesian_intro/practical-posteriors-likelihoods-priors.qmd
          - text: "MCMC Toy Example"
            href: teaching/bayesian_intro/practical-mcmc-toy.qmd
          - text: "Synthetic Controls"
            href: teaching/bayesian_intro/practical-synthetic-controls.qmd

format:
  html:
    theme: 
      - cosmo
      - custom-theme.scss
    include-in-header: assets/pdf-viewer-head.html
    include-after-body: _footer.html
    toc: true
    number-sections: false
    bibliography: references.bib

execute:
  freeze: auto

